#!/usr/bin/bash
#curl 'https://rol.redhat.com/rol/api/courses' -H $'cookie: csrftoken=QQ5L6kIlYW44Fyhtvjqzsg5My14vSE1e; sessionid=ruyy5cs8t958tlnvrs13w871emhvvtuu;'  --compressed | jq -r '.[].path' |uniq |egrep -iv  "^$|_|custom|vc|premium|plus|subscription|sku|gss|boot-camp|enablement|exam|support" | grep -E "[a-z][a-z][0-9]*[ea]*-[0-9]\.[0-9]"  > ../courses-list.txt

cat courses.json| jq '.[] | {"osversion"}| ."osversion"' | cut -d '"' -f2                                                     
