- name: ROL labs launcher
  hosts: localhost
  vars_files: credentials.yml
  vars:
    - lab_environment: rol
    - course_id: 
        - rh124-9.0
        - rh134-9.0
        - rh199-9.0
        - rh294-8.4
        - do180-4.10
        - do280-4.10
        - do288-4.10
        - do374-2.0
        - do447-2.8
    - rh_username: "{{ username | default('') }}"
    - rh_password: "{{ password | default('') }}"
    - counter: 0
        
  tasks:

    - name: generate hotp token
      shell: counter=$(cat ./counter); oathtool --hotp {{ secret }}  -c ${counter}; counter=$(( $counter + 1 )); echo $counter > ./counter
      register: token

    - name: Generate selenium script
      template:
        src: templates/lab-create.py.j2
        dest: "/tmp/lab-create.py"

    - name: Create courses
      shell: '/usr/bin/python3 /tmp/lab-create.py'
      register: selenium
