- name: ROL labs launcher
  hosts: localhost
  vars_files: credentials.yml
  vars:
    - lab_environment: rol
    - course_id: 
        - rh124-8.2
        - rh134-8.2
        - rh294-8.4
        - rh199-8.2
        - do180-4.6
        - do180-4.10
        - do280-4.6
        - do288-4.6
        - do378-1.11
        - do417-2.8
        - do447-2.8
    - rh_username: "{{ username | default('') }}"
    - rh_password: "{{ password | default('') }}"
    - counter: 0

  tasks:

    - name: generate hotp token
      shell: counter=$(cat ./counter); oathtool --hotp {{ secret }}  -c ${counter}; counter=$(( $counter + 1 )); echo $counter > ./counter
      register: token

    - name: Generate selenium script
      template:
        src: templates/lab-delete.py.j2
        dest: "/tmp/lab-delete.py"

    - name: Delete courses
      shell: '/usr/bin/python3 /tmp/lab-delete.py'
      register: selenium
