#!/usr/bin/env python3
"""
LX Tool - Simple wrapper for lx_toolbox CLI
"""

import sys
import os

# Add the parent directory to Python path so lx_toolbox can be imported
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from lx_toolbox.main import main

if __name__ == '__main__':
    main() 