apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/carias-rh/t1-shifts-main
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: t1-shifts-frontend
    app.kubernetes.io/component: t1-shifts-frontend
    app.kubernetes.io/instance: t1-shifts-frontend
    app.kubernetes.io/name: t1-shifts-frontend
    app.kubernetes.io/part-of: snow-t1
  name: t1-shifts-frontend
  namespace: lx-snow
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: t1-shifts-frontend:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /
    git:
      uri: https://github.com/carias-rh/t1-shifts-main
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - generic:
        secretReference:
          name: t1-shifts-frontend-generic-webhook-secret
      type: Generic
    - github:
        secretReference:
          name: t1-shifts-frontend-github-webhook-secret
      type: GitHub
    - type: ConfigChange
