apiVersion: batch/v1
kind: CronJob
metadata:
  name: snow-t1
  namespace: lx-snow
spec:
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      activeDeadlineSeconds: 14400
      template:
        spec:
          containers:
          - args:
            - /bin/sh
            - -c
            - /usr/bin/snow -t 'RHT Learner Experience'
            env:
            - name: DISPLAY
              value: ':99'
            - name: PYTHONUNBUFFERED
              value: '1'
            - name: T1_FRONTEND_OPENSHIFT_ROUTE
              value: https://t1-shifts-frontend-lx-snow.apps.tools-na100.dev.ole.redhat.com/
            image: quay.io/carias_rh/lx-toolbox:latest
            imagePullPolicy: Always
            name: snow-t1
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /runner
              name: snow-t1-1
            - mountPath: /app/lx-toolbox/playbooks/vars/credentials.yml
              name: credentials-volume
              subPath: credentials.yml
          - image: docker.io/metal3d/xvfb
            imagePullPolicy: Always
            name: xvfb
            ports:
            - containerPort: 99
              protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - emptyDir: {}
            name: snow-t1-1
          - name: credentials-volume
            secret:
              defaultMode: 420
              secretName: credentials
  schedule: '0 */4 * * *'
  startingDeadlineSeconds: 200
  successfulJobsHistoryLimit: 3
  suspend: false