- name: ROL labs launcher
  hosts: localhost
  vars_files: credentials.yml
  vars:
    - lab_environment: rol
    - course_id: 
        - rh124-9.0
        - rh134-9.0
        - rh199-9.0
        - rh294-9.0
        - do180-4.10
        - do188-4.10
        - do280-4.10
        - do288-4.10
        - do374-2.0
        - do447-2.8
    - rh_username: "{{ username | default('') }}"
    - rh_password: "{{ password | default('') }}"
    - counter: 0

  tasks:
    - name: Generate selenium script
      template:
        src: templates/rol-lab-delete.py.j2
        dest: "/tmp/delete.py"

    - name: Delete courses
      shell: '/usr/bin/python3 /tmp/delete.py'
      register: selenium
