- name: ROL labs launcher
  hosts: localhost
  vars_files: credentials.yml
  vars:
    - lab_environment: rol
    - course_id: ""
    - rh_username: "{{ username | default('') }}"
    - rh_password: "{{ password | default('') }}"
    - impersonate_username: ""
    - counter: 0
        
  tasks:
    - name: Generate selenium script
      template:
        src: templates/rol-lab-impersonate.py.j2
        dest: "/tmp/impersonate.py"

    - name: Impersonate
      shell: '/usr/bin/python3 /tmp/impersonate.py'
      register: selenium
