- name: ROL labs launcher
  hosts: localhost
  vars_files: vars/credentials.yml
  vars:
    - rh_username: "{{ username | default('') }}"
    - rh_password: "{{ password | default('') }}"

  tasks:
    - name: Generate selenium script
      template:
        src: templates/intercom-oncall.py.j2
        dest: "/tmp/intercom-oncall.py"

    - name: Activate intercom
      shell: '/usr/bin/python3 /tmp/intercom-oncall.py'
      register: selenium
